# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e00129179aee989c645daefffd67b024583790301299be6ec52ce689b324dc63b7de5fe6b4421fe24a7dd56e9448e8836b92ff8f035b65b1f0009288c67c0fc

test:
  secret_key_base: db0b94992c6305de82fedfd4aea6ab2681bc4963e32f688a85105ca8993ec61a694b4c13e5e1a732f96f22663f9c943a6f11072831a256a8e73a369e930f2332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
